/* eslint-disable */
// Generated by Wrangler — manually extended for Lyra (Spotify secrets + LyraAgent)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "LyraAgent";
  }
  interface Env {
    AI: Ai;
    LyraAgent: DurableObjectNamespace<import("./src/server").LyraAgent>;
    SPOTIFY_CLIENT_ID: string;
    SPOTIFY_CLIENT_SECRET: string;
  }
}
interface Env extends Cloudflare.Env {}
