/* eslint-disable */
// Generated by Wrangler — manually extended for Lyra
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "LyraAgent";
  }
  interface Env {
    AI: Ai;
    LyraAgent: DurableObjectNamespace<import("./src/server").LyraAgent>;
  }
}
interface Env extends Cloudflare.Env {}
